### ISSUE TITLE
how Imperatively trigger submit - missing useFormikContext

### ISSUE THREAD

**Issue by herbertpimentel** [jannikbuschke/formik-antd#101]
in formik examples (https://jaredpalmer.com/formik/docs/api/useFormikContext) we have useFormikContext hook that allows us to have access to { values, submitForm } so we can imperatively  trigger the form submition, this is helpful specially when we need submit from a antd modal.

any suggestion to accomplish that ?

**Comment by jannikbuschke** [comment]
this library does not alter how formik or ant design works. So usually you will wrap everything that you consider part of your form with the `formik` component. Inside that you can use `useFormikContext` just as usual (if you are using formik v2).

**Comment by herbertpimentel** [comment]
Hey @jannikbuschke thanks for the quick answer.... please can you check that https://codesandbox.io/s/formikantd-f1txw I am stuck with it.

**Comment by herbertpimentel** [comment]
Hey @jannikbuschke thanks for the quick answer. here is a solution for future reference

https://codesandbox.io/s/formikantd-f1txw

**Comment by jannikbuschke** [comment]
Your usage of refs looks a bit dubious to me.

Here is an example without: https://codesandbox.io/s/formikantd-shzig

you can just use useFormik in any child component within a `Formik` component

**Comment by herbertpimentel** [comment]
Yep, I see, but my original it is a bit more complex and uses ref because in the end is the the Modal OK button that triggers the submition
