### ISSUE TITLE
Select defaultValue not working

### ISSUE THREAD

**Issue by zhGio** [jannikbuschke/formik-antd#104]
defaultValue prop on <Select> does not work, while it works on Antd.

Reproduced on: https://codesandbox.io/s/formikantd-h1dor

**Comment by jannikbuschke** [comment]
As states are managed via formik, I would recommend to set a default value for your field on the "initialValues" object that is passed to the `Formik` component.

**Comment by zhGio** [comment]
Ugh I have some logic which programatically decides which dynamically rendered fields have default values and which not.. Using initial values there is not really an option

**Comment by jannikbuschke** [comment]
After thinking a bit about this, I think (unfortunately for you) initialValues is the only option that does make sense.
We use formik as a form state management library. Allowing setting initial values on the components _without_ having this reflected inside formik would be inconsistent. In the ui the initial value would be displayed, however formik would not yet have this value, and a submit would not be in sync with the ui state. Hence it is necessary to have this value on formiks initalValues.

**Comment by zhGio** [comment]
Ah I see, that absolutely makes sense.. Is it possible to link the defaultValue prop with the formik's initialValue for that field?

**Comment by jannikbuschke** [comment]
I don't think thats feasible.

**Comment by zhGio** [comment]
Alright. Thanks for the issue, I went around it by using Formik's setFieldValue when the default value loads, and understand why the defaultValue doesn't work.
