### ISSUE TITLE
Allow RangePicker to operate on two different fields (instead of one of type array)

### ISSUE THREAD

**Issue by mbryne** [jannikbuschke/formik-antd#105]
Greetings,

Thank you very much for your efforts on this,

Is there any possibility you could provide an example for how to use name attribute of the RangePicker for two different object properties?

**Comment by jannikbuschke** [comment]
This is currently not possible.
This might be worth to be implemented. The RangePicker could then have `name1` and `name2` props in this mode (and just a `name` prop with the current array mode).

**Comment by jannikbuschke** [comment]
Not sure if this would help you already, but if you just want the changed values in two separated fields, you could use the onChange prop to do this yourself.
The RangePicker would still use the `values` field to store and read the current value:

```jsx
<Formik
  initialValues={{
    values: null,
    value1: null,
    value2: null
  }}
  onSubmit={handleSubmit}
  render={(formik) => (
    <Form>
      <DatePicker.RangePicker name="values"
        onChange={values=>{
          console.log("values",values)
          formik.setFieldValue("value1",values[0])
          formik.setFieldValue("value2",values[1])
       }} />
/>
```

**Comment by jannikbuschke** [comment]
I decided against implementing this feature in favor of simplicity.
