### ISSUE TITLE
The change of checkbox, Radio would invoke the Formik form level validation twice

### ISSUE THREAD

**Issue by frankchendev** [jannikbuschke/formik-antd#113]
I used Formik form level validation with Yup, but the checkbox or radio button fields from Formik-antd didn't work properly. From debugging, I found that Formik.runValidationSchema was invoked twice when the checkbox was clicked. The first time, the checkbox field in values  had right value, but the second time, it just had past value. Other inputs field worked properly, just invoked the validation once.

Quick browser the source code in Formik-antd:

in Checkbox:
`        onChange={event => {
          setFieldValue(name, event.target.checked)
          setFieldTouched(name, true)
          onChange && onChange(event)
        }}`

in Input:
`        onChange={event => {
          onChange(event)
          $onChange && $onChange(event)
        }}
        onBlur={event => {
          onBlur(event)
          $onBlur && $onBlur(event)
        }}`

There is no explicit setting for field value or field touched in input code. But I am not sure it's root cause.

Thanks for your help. And let me know if you need any more information

**Comment by jannikbuschke** [comment]
There was the same problem with datepicker components recently.
I think validation runs twice because of the calls to setFieldValue and setFieldTouched. Should be easy to fix.

**Comment by frankchendev** [comment]
Thanks for your quick response
