### ISSUE TITLE
Ref support

### ISSUE THREAD

**Issue by stefanwille** [jannikbuschke/formik-antd#123]
Hello!

First late me thank you for this library. I find it very helpful and well built and I am glad that I didn't have to build this code myself!

Now my issue: I have a situation where I would like to get a ref (= `React.RefObject`) to an `Input`'s underlying `input` element, so that I can call `focus()` on it. The original Antd `Input` element supports this via the `ref` prop:

```
const inputRef = useRef();
useEffect(() => {
  inputRef.current.focus()
})
return <Input ref={inputRef} />
```
In formik-antd's `Input`, the `ref` prop is not available though. It would be great if you would add it. 

I have tried to build a PR myself by using `React.forwardRef()` and struggled with setting `Input.Password`.

**Comment by jannikbuschke** [comment]
hey, thanks for the compliment.

This is weird, we pass down all props to the underlying component, so I would expect this to work. But it does not, and even typescript complains. I am not sure where the problem is though. Any help in identifying this issue would be greatly appreciated.

**Comment by stefanwille** [comment]
I think the reason that `ref` is not propagated down is that it is a special prop, like `key`.
`Input` has to use forwardRef itself.

I have built the following component as a workaround.

**Comment by stefanwille** [comment]
```
import React, { Ref } from 'react';
import { Input as $Input } from 'antd';
import { FieldProps, Field as FormikField, FastField } from 'formik';

import { InputProps as $InputProps } from 'antd/lib/input';

export interface FormikFieldProps {
  name: string;
  validate?: (value: any) => undefined | string | Promise<any>;
  fast?: boolean;
}

export const Field: React.FC<FormikFieldProps> = ({
  fast,
  children,
  ...restProps
}) => {
  if (fast) {
    return <FastField {...restProps}>{children}</FastField>;
  }

  return <FormikField {...restProps}>{children}</FormikField>;
};

export default Field;

export type InputProps = FormikFieldProps & $InputProps;

export const InputWithRef = React.forwardRef(
  (
    {
      name,
      validate,
      fast,
      onChange: $onChange,
      onBlur: $onBlur,
      ...restProps
    }: InputProps,
    ref: Ref<$Input>
  ) => (
    <Field name={name} validate={validate} fast={fast}>
      {({ field: { value, onChange, onBlur } }: FieldProps) => (
        <$Input
          ref={ref}
          name={name}
          value={value}
          onChange={event => {
            onChange(event);
            $onChange && $onChange(event);
          }}
          onBlur={event => {
            onBlur(event);
            $onBlur && $onBlur(event);
          }}
          {...restProps}
        />
      )}
    </Field>
  )
);
```

**Comment by stefanwille** [comment]
This is mostly a copy of `Input`, with `React.forwardRef` added in.

**Comment by jannikbuschke** [comment]
This looks good to me (after reading the docs a bit https://reactjs.org/docs/forwarding-refs.html). Feel free to open a PR (or wait for me, Ill probably will implement this soonish).

**Comment by stefanwille** [comment]
My problem with this was how to set Input.Password on Input after applying React.forwardRef. I have not fix for this yet.

**Comment by jannikbuschke** [comment]
ok I see what you mean. This combination of static/forwardRefs and typescript does not play super nicely together. Somehow the React.forwardRef type changes the typescript definition, i.e. the static Password and TextArea props are missing.

This comment https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34757#issuecomment-488848720 might provide a reasonable soluton.

**Comment by jannikbuschke** [comment]
It gets a bit ugly though. I.e. in this example the static Password property is expected, thats why I first cast the Input type to any and then to Props:

```jsx
interface Props extends React.RefForwardingComponent<$Input, InputProps> {
  Password: any
}

export const Input: Props = (React.forwardRef(
  (
    {
      name,
      validate,
      fast,
      onChange: $onChange,
      onBlur: $onBlur,
      ...restProps
    }: InputProps,
    ref: React.Ref<$Input>,
  ) => (
    <Field name={name} validate={validate} fast={fast}>
      {({ field: { value, onChange, onBlur } }: FieldProps) => (
        <$Input
          ref={ref}
          name={name}
          value={value}
          onChange={(event) => {
            onChange(event)
            $onChange && $onChange(event)
          }}
          onBlur={(event) => {
            onBlur(event)
            $onBlur && $onBlur(event)
          }}
          {...restProps}
        />
      )}
    </Field>
  ),
) as any as Props)
```

**Comment by stefanwille** [comment]
Oh, I understand... kind of. I will try that.

**Comment by stefanwille** [comment]
I have looked at AntD's original source for Input to find out how they have solved the problem, and they use a class component. Would you be open to class components for Input and friends?

**Comment by jannikbuschke** [comment]
Na, that would make it way uglier in my opinion.

**Comment by jannikbuschke** [comment]
Ive tried to implement ref support. Can you test v 1.9.0-beta.1 and give feedback?

**Comment by stefanwille** [comment]
Very cool!

I have tried it and made a repo here: https://github.com/stefanwille/formik-antd-experiment

I get:

```bash
$ tsc
src/App.tsx:10:27 - error TS2749: 'Input' refers to a value, but is being used as a type here.

10   const inputRef = useRef<Input>(null);
                             ~~~~~


Found 1 error.
```

I think the trick used to set Input.Password causes this.

**Comment by jannikbuschke** [comment]
There seems to be a typescript issue (and my knowledge of refs are quite limited). However when ignoring this it should work. I.e. I did the following:
```jsx
import React, { useRef, useLayoutEffect, useEffect } from "react";
import { Form, Input } from "formik-antd";
import { Formik } from "formik";
import "./App.css";
import "antd/dist/antd.css";
import { message } from "antd";

const App = () => {
  const inputRef = useRef<any>(null);

  useEffect(() => {
    if (!inputRef.current) {
      console.error("missing ref")
    }
    inputRef.current.focus();
  },[]);

  return (
    <div className="App">
      <Formik
        initialValues={{ firstName: "", age: 20, newsletter: false }}
        onSubmit={(values, _formikHelpers): any => {
          message.info(JSON.stringify(values, null, 2));
        }}
        render={formikApi => (
          <Form>
            <Input name="firstName" placeholder="First Name" ref={inputRef} />
          </Form>
        )}
      />
    </div>
  );
};

export default App;
```

(Note I added an empty dependency array to the useEffect hook, however this does not make any difference). Also your version might already work.

What I noticed is that the Input component does not get focused if the browser window is not active.  So to test if it really works/does not work you need to focus the browser and to a refresh there.

**Comment by stefanwille** [comment]
Yes, this works fine 👍

**Comment by stefanwille** [comment]
Okay, I just saw that Ant Design' `Input` itself doesn't implement proper ref forwarding to the underlying `HtmlInputElement`, it only offers a ref to the `Input` class component instance. And the reason why `focus()` works is that the class component forwards some calls to the underlying `input` ref that is holds privately, for example:

```
class Input {
  ...
  focus() {
      this.input.focus();
  }
  ...
}
```

The actual `this.input` ref is never exposed. So the ref we get is to the Ant Design component. Which is not great, but works.

**Comment by stefanwille** [comment]
I have experimented with building a class component, but the typing issue remains weird.

**Comment by stefanwille** [comment]
```
/* eslint-disable react/jsx-pascal-case */
import { Input as $Input } from "antd";
import { FieldProps } from "formik";
import React, { RefAttributes } from "react";
import {
  InputProps as $InputProps
  // PasswordProps as $PasswordProps,
  // TextAreaProps as $TextAreaProps
} from "antd/lib/input";
// import { FormikFieldProps } from "../FieldProps";
import { FormikFieldProps } from "./FieldProps";
// import Field from "../field";
import Field from "./field";

export type InputProps = FormikFieldProps & $InputProps & RefAttributes<$Input>;

export class Input extends React.Component<InputProps> {
  render() {
    const {
      name,
      validate,
      fast,
      onChange: $onChange,
      onBlur: $onBlur,
      ref,
      ...restProps
    }: InputProps = this.props;

    return (
      <Field name={name} validate={validate} fast={fast}>
        {({ field: { value, onChange, onBlur } }: FieldProps) => (
          <$Input
            name={name}
            value={value}
            onChange={event => {
              onChange(event);
              $onChange && $onChange(event);
            }}
            onBlur={event => {
              onBlur(event);
              $onBlur && $onBlur(event);
            }}
            ref={ref}
            {...restProps}
          />
        )}
      </Field>
    );
  }
}

export default Input;
```

**Comment by stefanwille** [comment]
Oops, I have closed the issue accidentally.

**Comment by stefanwille** [comment]
Here the type of the exposed ref attribute is `RefAttributes<Input>` and not `RefAttributes<$Input>` as required to make this work.

**Comment by stefanwille** [comment]
I have tried Input from version 1.9.0 and it works fine for me. Therefore I am closing this issue.
