### ISSUE TITLE
2.0 Validation seems to always give error feedback

### ISSUE THREAD

**Issue by heuristicAL** [jannikbuschke/formik-antd#124]
Validation seems to always give error feedback, even though the Formik props don't mention there being an error.
This happens for both my Select and Input controls. Might also happen to all others but I have not tested that yet.

I'm using antd-formik 2.0-beta and antd 4.0.0-rc3

**Comment by jannikbuschke** [comment]
Hi @heuristicAL,

Im not sure exactly what you mean. Can you provide an example with the following codesandbox: https://codesandbox.io/s/github/jannikbuschke/formik-antd-example/tree/release/v2.0

**Comment by heuristicAL** [comment]
Hey @jannikbuschke , thanks for the quick reply! I just updated to `"formik-antd": "2.0.0-beta.1"` as well as `"antd": "4.0.0-rc.3"` and aI am not running into the issue anymore. Seems to have been a freak bug that was already fixed!
