### ISSUE TITLE
<Select> field's validation errors are not shown if field is untouched

### ISSUE THREAD

**Issue by kissthom** [jannikbuschke/formik-antd#127]
###  The problem 
I use Select components with placeholder values in my forms. And in many cases these fields are mandatory.
And normally works everything just fine, but when the user does not touch the select (mandatory field) before hitting submit the validation error for that field will not be shown.

So if I try to use the Select normally, I don't provide an initial value for the field, I hit submit. Although error will be populated, it will not show up on the UI because the field is not touched.
I understand the reason for it, formik only sets the fields to touched which have a value. And if I don't provide an initial value for the field or select a value manually (touch it) then the field will not have a value. 

```javascript
       <Formik
        validationSchema={Yup.object().shape({
          select: Yup.string().required()
        })}
      >
        {formikProps => (
          <Form>
            <FormItem name="select">
              <Select name="select" placeholder="Select something">
                <Select.Option value="jack">Jack</Select.Option>
                <Select.Option value="lucy">Lucy</Select.Option>
              </Select>
            </FormItem>
            <SubmitButton>Submit</SubmitButton>
          </Form>
        )}
      </Formik>
```

Okay then, I can solve this issue by providing an initial value for the field like an empty string (or null).  If I do that, I get my validation error finally, but the placeholder does not work any more :(. 
And now is the reason is the ant design select component because it shown the placeholder only if the value for the select is undefined.

So right now in this scenarioI have to choose between validation error or placeholder because the two libs expect other things from us.
 
### Suggestion solution

This issue could be solved by changing only one line in the Select component. By mapping empty string to undefined, we make formik happy, because now we can provide an initial value for the field as [strongly suggested](https://github.com/jaredpalmer/formik/issues/445#issuecomment-366952762) and at the same time ant design's Select will also show the placeholder because now it gets undefined as value in case of empty string.

```typescript
<Field name={name} validate={validate} fast={fast}>
      {({
        field: { value },
        form: { setFieldValue, setFieldTouched }
      }: FieldProps) => (
        <$Select<any>
          onChange={(value, option) => {
            setFieldValue(name, value);
            onChange && onChange(value, option);
          }}
          onBlur={value => {
            setFieldTouched(name);
            onBlur && onBlur(value);
          }}
          value={value === "" ? undefined : value} // ! you can provide now empty string as initial value and placeholder still works
          {...restProps}
        >
          {children}
        </$Select>
      )}
    </Field>
```

### Example 
You can find all the cases described above in this codesandbox:
https://codesandbox.io/s/formik-antd-select-validation-or-placeholder-gm2id

P.S.: Thanks for the great lib! 🚀

**Comment by jannikbuschke** [comment]
Hi @kissthom ,

Thanks for bringing this up and also providing a solution!

The fix should be available in 1.8.1 and 1.9.0-beta.5

**Comment by jannikbuschke** [comment]
@all-contributors add @kissthom for bug

**Comment by kissthom** [comment]
Hi @jannikbuschke ,

least one can do in exchange for getting such a useful library :). Thanks for fixing it so quickly! Cheers!
(I guess it's okay if I close this issue now)
