### ISSUE TITLE
Add support to the final Antd 4.0.0

### ISSUE THREAD

**Issue by mfactorial** [jannikbuschke/formik-antd#134]
Currently I can't use the formik-antd with the latest stable release (4.0.0) of Antd. The problem is the following: 
```
Failed to compile.
./node_modules/formik-antd/es/mention/index.js
Attempted import error: 'Mention' is not exported from 'antd' (imported as '$Mention').
```

**Comment by jannikbuschke** [comment]
are you using formik-antd v2 beta?
The mention component was removed in antd v4 / formik-antd v2.

**Comment by anonrig** [comment]
Is there any timeline for this? We're waiting for formik-antd to upgrade :)

**Comment by jannikbuschke** [comment]
you can use the v2 beta, it should work with antd v4.0.0.
There are only minors that dont work yet (Mentions component for example).

Else I am working on it this weekend to double check things and give update notes.

**Comment by anonrig** [comment]
Wow, thank you for the fast response. Working on a friday night. Appreciate your passion! Just a quick question:

How can I install v2 beta? I couldn't find it in the releases

**Comment by jannikbuschke** [comment]
there are all versions listed: https://www.npmjs.com/package/formik-antd
2.0.0-beta.2 is the latest beta
on github I still need to automate release creation, so not all versions are listed here...
