### ISSUE TITLE
AutoComplete OnChange No overload match this call

### ISSUE THREAD

**Issue by teeyuseng** [jannikbuschke/formik-antd#138]
after import AutoComplete component ，will suffer 'No overload match this call'

**Comment by teeyuseng** [comment]
also can't set AutoComplete .Option

**Comment by jannikbuschke** [comment]
Hi @teeyuseng,

Can you provide a reproduction with the following codesandbox? https://codesandbox.io/s/damp-darkness-y1q01?file=/src/overview.tsx

**Comment by teeyuseng** [comment]
Thanks for feedback.
->
I check out  AutoComplete .Option is defined in class AutoComplete not in AutoCompleteProps
after use const {Option} = AutoComplete , will suffered  'Option' does not exist.
I use 'datasource'  to set options to solve my problem

->
about onChange method ,
 
![problem1](https://user-images.githubusercontent.com/41940914/78904217-c9fe3600-7aae-11ea-9710-59046b7dd9b5.png)
![problem2](https://user-images.githubusercontent.com/41940914/78904223-cbc7f980-7aae-11ea-9fae-95d726d0ac5f.png)
