### ISSUE TITLE
How get casted yup values?

### ISSUE THREAD

**Issue by Valtas** [jannikbuschke/formik-antd#142]
<Formik
initialValues={initialValues}
validationSchema={validationSchema}
onSubmit={(castedValues) => ... }
>

**Comment by Valtas** [comment]
<Formik
                initialValues={initialValues}
                validationSchema={validationSchema}
                onSubmit={(castedValues) => ... }
            >

**Comment by jannikbuschke** [comment]
How would you do it with formik only?
This library is not concerned with yup, and it does not alter the Formik container.
