### ISSUE TITLE
SubmitButton inside form tag with onSubmit handler causes submit handler to be called twice

### ISSUE THREAD

**Issue by n3v3rf411** [jannikbuschke/formik-antd#15]
If I set the `htmlType` to `button`, it won't submit twice but form submit using enter key doesn't work anymore.

Sample code:
```jsx
<Formik initialValues={{ username: "", password: "" }} onSubmit={this.handleSubmit}>
  {props => (
      <form className={styles.login} onSubmit={props.handleSubmit}>
        <FormItem name="email">
          <InputField name="email" placeholder="Email" autoComplete="username"
                      prefix={<Icon type="user" style={{color: 'rgba(0,0,0,.25)'}}/>}/>
        </FormItem>
        <FormItem name="password">
          <InputField name="password" type="password" placeholder="Password" autoComplete="current-password"
                      prefix={<Icon type="lock" style={{color: 'rgba(0,0,0,.25)'}}/>}/>
        </FormItem>
        <FormItem>
          <SubmitButton className={styles.submit} type="primary" htmlType="submit" size="large">
            Login
          </SubmitButton>
        </FormItem>
      </form>
  )}
</Formik>
```

**Comment by jannikbuschke** [comment]
May I ask why are you using the `<form>` component? Is it for triggering submit on enter key or also some accessibility thing?
Up until today I tried to avoid using `<form>` inside `<Formik>`, as accidentally other buttons might trigger form submittion (I think if htmlType or type is not set).

**Comment by n3v3rf411** [comment]
Yes it is for triggering submit on enter key. Also, the examples in formik uses the form tag. If you have an input type `password` not wrapped in a form, chrome logs the following warning in the console:

`[DOM]  Password field is not contained in a form: (More info: https://goo.gl/9p2vKq)`

**Comment by jwmann** [comment]
Try removing `htmlType="submit"` from `<SubmitButton />`

**Comment by jannikbuschke** [comment]
@n3v3rf411  I am not yet sure what the best approach here is. As a workaround (or solution?) you can set htmlType and onClick props of the SubmitButton like so:
```jsx
<form onSubmit={props.handleSubmit}>
  <SubmitButton
    type="primary"
    htmlType="submit"
    size="large"
    onClick={() => {}}
  >
    Login 
  </SubmitButton>
```

**Comment by n3v3rf411** [comment]
Indeed it's because of the `onClick` handler in SubmitButton. This will suffice for now!

For me, the default handlers in onClick should be removed and have the user manually set onClick if they do not enclose the input elements in a form tag. I'm not sure if it's a common practice but checking ant-design-pro pages source codes, ant design form documentation, and formik documentation, they all do.

**Comment by jannikbuschke** [comment]
#29 I removed the custom onClick handler on the SubmitButton. Means a `<form>`, `<Form>` (formik helper) or `<Form>` (formik-antd) helper are needed for SubmitButton to work
