### ISSUE TITLE
DatePicker Not Working

### ISSUE THREAD

**Issue by faizankhan1995** [jannikbuschke/formik-antd#154]
I am using below code to set value of Date, but submit button doesnot gets enabled even after the date is selected.
<FormItem name="RoutePermitExpiryDate" label="Route Permit Expiry Date" required={true}>
              <DatePicker name='RoutePermitExpiryDate' />
</FormItem>

I am using yup for validation. RoutePermitExpiry: yup.date().required(),

**Comment by jannikbuschke** [comment]
Hi @faizankhan1995 , can you share a minimal reproduction?

**Comment by faizankhan1995** [comment]
`import React from "react";
import { Form, FormItem, SubmitButton, DatePicker } from "formik-antd";
import * as yup from "yup";
import { Formik } from "formik";
import "./styles.css";

export default function App() {
  const validationSchema = yup.object({
    LisenceIssueDate: yup.date().required(),
    LisenceExpiryDate: yup.date().required()
  });

  return (
    <Formik
      initialValues={{}}
      validationSchema={validationSchema}
      onSubmit={(values) => console.log(values)}
    >
      {() => (
        <Form className="form-input">
          <FormItem name="LisenceIssueDate" label="Lisence Issue Date">
            <DatePicker name="LisenceIssueDate" />
          </FormItem>
          <FormItem name="LisenceExpiryDate" label="Lisence Expiry Date">
            <DatePicker name="LisenceExpiryDate" />
          </FormItem>

          <SubmitButton className="input-form-submit-button">
            Submit
          </SubmitButton>
        </Form>
      )}
    </Formik>
  );
}
`

Can you make it work ?

**Comment by faizankhan1995** [comment]
```
import React from "react";
import { Form, FormItem, SubmitButton, DatePicker } from "formik-antd";
import * as yup from "yup";
import { Formik } from "formik";
import "./styles.css";

export default function App() {
  const validationSchema = yup.object({
    LisenceIssueDate: yup.date().required(),
    LisenceExpiryDate: yup.date().required()
  });

  return (
    <Formik
      initialValues={{}}
      validationSchema={validationSchema}
      onSubmit={(values) => console.log(values)}
    >
      {() => (
        <Form className="form-input">
          <FormItem name="LisenceIssueDate" label="Lisence Issue Date">
            <DatePicker name="LisenceIssueDate" />
          </FormItem>
          <FormItem name="LisenceExpiryDate" label="Lisence Expiry Date">
            <DatePicker name="LisenceExpiryDate" />
          </FormItem>

          <SubmitButton className="input-form-submit-button">
            Submit
          </SubmitButton>
        </Form>
      )}
    </Formik>
  );
}
```

Can you make it work ?

**Comment by faizankhan1995** [comment]
@jannikbuschke  any update on this ?
