### ISSUE TITLE
Issues with input validation css styling when used within Ant Design Pro

### ISSUE THREAD

**Issue by yhrchan** [jannikbuschke/formik-antd#157]
Hi,

I've been using Ant Design Pro following the getting started steps in https://pro.ant.design/docs/getting-started along with Formik and formik-antd. Testing this in the simplest case with a formik-antd input with schema validation using Yup. It doesn't seem to style the validation errors properly (I've attached a screenshot where the validation error message is just black text with no red color bordering the input). On the other hand, I've also tested it using UmiJS getting started (https://umijs.org/docs/getting-started#scaffold) along with formik-antd with the same input with schema validation using Yup. This time the validation error message is styled properly (see attached screenshot). Scratching my head, would be nice if I could use Formik and formik-antd within Ant Design Pro.

![2020-08-28 (1)](https://user-images.githubusercontent.com/3683552/91597668-602dde00-e922-11ea-83c8-44395e6717a4.png)
![2020-08-28](https://user-images.githubusercontent.com/3683552/91597707-6328ce80-e922-11ea-86e5-42df87f8ecc5.png)

Thanks!

**Comment by jannikbuschke** [comment]
hi @yhrchan, sorry Im not able to help on this as I am not using ant design pro. Maybe someone else can assist here.

**Comment by yhrchan** [comment]
Thanks @jannikbuschke anyways. In case anyone runs into the same problem, I was able to resolve it by importing the following. Not sure the underlying reason, but it works.

import ProTable from '@ant-design/pro-table';
