### ISSUE TITLE
Setting an Input value renders Input as uneditable

### ISSUE THREAD

**Issue by rigorio** [jannikbuschke/formik-antd#162]
I can't really paste my code here for legality reasons, but it's basically the same as the provided example in the wiki.

```
import React from 'react'
import { Form, Input, InputNumber, Checkbox } from 'formik-antd'
import { Formik } from 'formik'

function App() {
  return (
    <Formik
      {/* default/initial values are set on the Formik container: */ }
      initialValues={{ firstName: '', age: 20, newsletter: false }}
      render={() => (
        <Form>
          {/* every formik-antd component must have the 'name' prop set: */}
          <Input name='firstName' placeholder='First Name' value='why' />
          {/* the rest of the api stays as is */}
          <InputNumber name='age' min={0} />
          <Checkbox name='newsletter'>Newsletter</Checkbox>
        </Form>
      )}
    />
  )
}
```

Except that my input has a value. The value comes from a set constant in a useEffect that has a props as a dependency.

So now basically the problem I have is if I set a value to the Input, I simply cannot edit the text in the Input.

**Comment by rigorio** [comment]
Just a bit more explanation. So what I'm basically trying to achieve is I'm editing an entity. So I'm setting the selected entity's values to the formik-antd inputs to edit the values. But again the problem is that I cannot edit the Inputs once their values are set.

**Comment by rigorio** [comment]
Working solution:
```
    useEffect(() => {
        if (id !== undefined) {
            (async ()=>{
                let res = await fetchData(id );
                setName(res.data.name)
            })()
        }
    }, [id])
    const [name, setName] = useState("");"
...
    const valueChangeHandler = (value) => {
      setName(value.target.value)
    }
...
    <Input name="name" value={name} onChange={valueChangeHandler}/>

```

So I need to do it manually via React Hooks. I think this is a bit too cumbersome especially if you have a lot of Inputs. Editing an `Input` that has a set `value` should be made possible.

**Comment by jannikbuschke** [comment]
Hi @rigorio , you should set initial values via the Formik container.

Setting the value prop of any formik-antd component is not recommended. This library does exactly handle this for you, so that formik and ant design are synced without having the developer explicitly set the value and handle the onChanges...

**Comment by rigorio** [comment]
Hi @jannikbuschke. Can the initial values be dynamic?
