### ISSUE TITLE
Typescript: Slider props import no longer working with Ant Design 4.8.1

### ISSUE THREAD

**Issue by SnarkieDesign** [jannikbuschke/formik-antd#164]
Since updating Ant Design to 4.8.1, the formik-antd Select component causes Typescript errors.

I believe the issue lies in line 6 of [slider/index.tsx](https://github.com/jannikbuschke/formik-antd/blob/master/src/slider/index.tsx):
`import { SliderProps as $SliderProps } from 'antd/lib/slider'`

Ant Design have split the props interfaces into **SliderSingleProps and SliderRangeProps**. [This is the Ant Design commit that broke things](https://github.com/ant-design/ant-design/commit/6d5c3fe953968d395304c58204e6ba7bcbe6c458)

**Comment by jannikbuschke** [comment]
Hi @SnarkieDesign , thanks for bringin this up.

v 2.1.0-beta.1 should solve this issue. If not pls reopen.
