### ISSUE TITLE
select multiple validation errors not shown

### ISSUE THREAD

**Issue by linchen2chris** [jannikbuschke/formik-antd#165]
I have a field which is an array, with initial value [], I will validate it by `Yup.array().required('required')`, but its touched is false when submit, and validation error can not shown.

**Comment by linchen2chris** [comment]
fix this and create a PR for this, waiting for merge https://github.com/jannikbuschke/formik-antd/pull/166

**Comment by linchen2chris** [comment]
will close after PR merged

**Comment by MaruniakS** [comment]
I faced up with the same issue. Sometimes error is shown, but it hides after submitting form
`Yup.array().of(Yup.string()).min(1, 'Error text')`

**Comment by linchen2chris** [comment]
@MaruniakS actually the error is there, but array field has some problem with `touched`, it will hide the error

**Comment by vprsendictx** [comment]
@MaruniakS yeap, instead of setting touched to `true` for multi-select, it sets touched to an empty array on form submit validation.

**Comment by linchen2chris** [comment]
https://github.com/jannikbuschke/formik-antd/pull/166 fixed it
