### ISSUE TITLE
Memory leak using Select

### ISSUE THREAD

**Issue by JoFont** [jannikbuschke/formik-antd#177]
Using any combination of the Select field from "formik-ant" results in a memory leak of some sorts. The select dropdown never opens and the app crashes. Using the SelectInput directly from Ant Design outside of a FormItem works fine but defeats the purpose of using this library.

```
<FormItem name="title" label="Title" className="col-span-2 md:col-span-1">
  <Select name="title" options={options} />
</FormItem>
```

Notes:
- I'm using React concurrent mode.
- Setting options declaratively produces the same error.
- After some inspection on the crashed app, the only error I can see is a violation warning as seen below.
<img width="328" alt="826d5d579ace8a60b33b5c63a22f105f" src="https://user-images.githubusercontent.com/8378956/106390548-cbec0980-63e0-11eb-9a6b-270d66c83506.png">

Thank you for your help.

**Comment by JoFont** [comment]
Follow up on this issue: downgrading Ant Design version to **4.1.0** from **4.11.2**  seemd to work.

**Comment by RikeshThapa** [comment]
2022 update: I managed to resolve this by updating formik-antd and antd to their latest versions (2.0.4 and 4.22.6 respectively).
Furthermore you need to check which version of React you are running. Some changes were made to React-DOM in React 18.1 that may cause some incompatibilities between React <> Formik-antd <> antd . 

I first tried to downgrade antd, but this causes issues with React 18.
