### ISSUE TITLE
Is this package really not supposed to support React 17+ ?

### ISSUE THREAD

**Issue by mikedotJS** [jannikbuschke/formik-antd#178]
Hey,

Sorry if this is not the place to ask this.

React 17 is months old now and this very useful package indicates that it has a peer dependency on React ">= 16.8.0 < 17".

Is React 17 really not supported yet? If not, will it be in the near future?

I'm really considering to use `formik-antd` for a real-world app but i absolutely need to know if the future versions of React will be compatible with it.

Thank you!

**Comment by jannikbuschke** [comment]
Hi @mikedotJS,
I am not entirely sure if ant design works with react 17 yet: https://github.com/ant-design/ant-design/issues/26136

But this library will most likely work with react 17. If not I will work on it.

**Comment by rafalluksza** [comment]
We're using it with React 17 and everything works fine!

**Comment by jamov** [comment]
Would it be possible to update the peer dependencies since the package seems to be working with React 17?

**Comment by jannikbuschke** [comment]
@jamov v2.1.0-beta.4 should solve this problem

**Comment by jannikbuschke** [comment]
also fixed in 2.0.3
