### ISSUE TITLE
Html Label (in testing contexts) and a11y behavior not optimal 

### ISSUE THREAD

**Issue by jannikbuschke** [jannikbuschke/formik-antd#25]
> Can you elaborate a bit which labels you mean exactly?

Sure, here's a forked example of your CodeSandbox: https://codesandbox.io/s/y257p4l8z9

**Edit:** as a counter-example, look at `antd`'s own CodeSandbox to see how the DOM differs: https://codesandbox.io/s/kw79qx5w15

The `label` element for `[name=userName]` does not have a `for="userName"`, which breaks things like `react-testing-library`'s `getByLabelText` and forces me to fallback to less optimal methods for finding and filling inputs, and breaks some browser / a11y behavior.

I have a feeling this is some sort of props issue, but honestly just have not had time to examine further.

(P.S. Thanks for making this!)

_Originally posted by @joshsmith in https://github.com/jannikbuschke/formik-antd/pull/23#issuecomment-488612356_

**Comment by jannikbuschke** [comment]
@joshsmith can you give me sample code that you would _expect to run successfully_?

**Comment by joshsmith** [comment]
```
<FormItem name="userName" label="Name">
  <Input name="userName" />
</FormItem>
```

**Comment by jannikbuschke** [comment]
The antd example is imho overly complicated and uses some HOC wrappers and these getFieldDecorator() helpers. This is definitely not how I _usually_ would want to write my forms...

this code 
```jsx
import * as React from "react";
import { Formik } from "formik";
import { Input, Form } from "@jbuschke/formik-antd";
// import { Input, Form } from "antd";

export const Sample = () => {

  return <Formik initialValues={{ firstName: "bob" }} onSubmit={() => { }}>
    <div style={{ margin: 50 }}>
      <Form.Item name="firstName" label="First Name">
        <Input data-testid="firstname" name="firstName" />
      </Form.Item>
    </div>
  </Formik>
}
```
allows to switch back and forth between pure antd and formik-antd style (in formik-antd case a name prop for Form.Item needs to provided, which is the only difference) and produces very similar results:

![image](https://user-images.githubusercontent.com/5894881/58054687-9eebba80-7b5b-11e9-800d-bcd9fcfa8e54.png)

**Comment by joshsmith** [comment]
I don’t think we’re talking about the same thing. I’m referring specifically and only to the `for` HTML attribute on `label`.

**Comment by joshsmith** [comment]
Read this document on MDN for more context about the importance of associating a label with a labelable element like input: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by jannikbuschke** [comment]
For me it seems this is more an ant d issue. I am trying to get it working with a minimal ant d setup like this:
```
      <Form.Item for="firstName" name="firstName" label="First Name">
        <Input data-testid="firstname" name="firstName" />
      </Form.Item>
```
(Note these items can be either imported from antd or formik-and)

In the ant d example the "for" attribute does not appear ín the html. Thats why I think this is an ant design issue / we dont yet understand how to make it work there.

**Comment by joshsmith** [comment]
Looking into this again, it seems like this does work to produce the `for` attribute:

```
<FormItem id="userName" label="Name">
  <Input id="userName" name="userName" />
</FormItem>
```

That may be sufficient to close this issue, unless you want to keep it open and monitor the other a11y issues identified in the linked one.

**Comment by jannikbuschke** [comment]
Ill keep this open to also monitor the ant design issue.

**Comment by ghola** [comment]
I don't think it's an ant design issue. Using any version of ant I can make it work as expected, with label having the proper `for` value. You can also see it working in the ant components page on their website.

The problem seems to lie in the `FormItem` component of the `formik-antd` library which does not pass the `name` property to the wrapped antd `Form.Item`.

https://github.com/jannikbuschke/formik-antd/blob/17255f49630d426b1f64427eecc1cdef0ad7cf8f/src/form-item/index.tsx#L37-L62

`restProps` does not contain the name.

**Comment by jannikbuschke** [comment]
@ghola cool thanks for investigating. Will update soon.

**Comment by jannikbuschke** [comment]
I think this issue is now solved.
Using 
```jsx
<FormItem htmlFor="firstName" name="firstName" label="First name">
  <Input id="firstName" name="firstName" />
</FormItem>
```
if the user clicks the label "First Name" the Input will be focused. I assume the html "for" attributes are now properly set. I also assume react testing library now is easier to use in such cases (I used testcafe in another project and it was nice to let the test runner just click the label, and not search for implementation details like attributes or css classes).

I didnt properly investigate this, so if anyone can report on this it would be greatly appreciated.

**Comment by jannikbuschke** [comment]
In order to reduce specifying the field names a quadrillion times, I am thinking to implement #140 or something along the lines.

**Comment by jannikbuschke** [comment]
Im thinking about FormItem improvements in the context of #41

**Comment by C-Higgins** [comment]
It should not require setting htmlFor. Standard AntD works with just a FormItem having a name. This package just needs to pass the name field onto the FormItem as @ghola said.
