### ISSUE TITLE
FastField Support

### ISSUE THREAD

**Issue by jwmann** [jannikbuschke/formik-antd#26]
I'm really happy how this project has evolved, I feel like it's at a really good spot right now. 👍

https://jaredpalmer.com/formik/docs/api/fastfield
This is just a feature request for the future of this package. Could be really useful for some ( I might even try them out for optimization ) 

I believe the FastField uses the same API as Field so it shouldn't be too crazy to implement.
Not sure if we should make new components for each (but using FastField) or make some kind of switch in the component itself.
Either way, I'd hope it maintains our clean coding standard so far.

**Comment by jannikbuschke** [comment]
Y would be cool if FastField would be supported. However I think that _usually_ using Field will be fast enough, especially in production builds (formik also got faster with recent versions).

As I didn't yet encounter performance issues (and "premature optimization is the root of all evil") I will be reluctant to focus on this topic (unless I hit performance problems).

Contributions would be very welcome. I think these components should be separated from the current ones (to not overload them with responsibilities). Introducing new components with a *Fast suffix could be an option. Also putting them as static components on existing ones, like <Input.Fast ... /> ?
Or if possible allow them to be imported from a subnamespace/submodule (not sure about the correct javascript terms) and just use the same names. Like
```
import { Input } from "..formik-antd/fast"
```

**Comment by babbarankit** [comment]
@jannikbuschke I think subnamespace will be good option. I can work on the PR.

**Comment by jannikbuschke** [comment]
@babbarankit I recently noticed that any exported component is available like `import { Component } from "@jbuschke\formik-antd\lib\path-to-component`

 This is what you mean or?

**Comment by voxtex** [comment]
I think this a great idea, I see performance issues with Formik when I have 25+ fields. Although I disagree it should be a separate component, why not make it a property on all existing components `fast={true}` and then use `Field` vs `FastField` in the component itself? Would reduce a lot of code duplication.

**Comment by jannikbuschke** [comment]
Do you see performance problems in debug mode or with your production build?

**Comment by dbousamra** [comment]
I see problems in production build. I have ~ 30 fields in my form across several pages.

**Comment by gabrielberlanda** [comment]
Hi @jannikbuschke, I'm having problems without fast field too, at my company we're trying to go prod asap, so I made a fork and implemented a wrapper for Formik Field with a fastMode support...
I'm starting now in open source, if u have time, check my fork implementation and if its ok I can send a PR fixing it.

[Field with fast mode support implementation](https://github.com/gabrielberlanda/formik-antd/blob/master/src/field/index.tsx)

**Comment by jannikbuschke** [comment]
Your approach looks reasonable to me. Feel free to open a PR.

**Comment by jannikbuschke** [comment]
FastField support is available in v1.9.0-beta.0
 https://github.com/jannikbuschke/formik-antd#fastfield-support

Any feedback is appreciated!
