### ISSUE TITLE
Using Antd Table with formik

### ISSUE THREAD

**Issue by delyanr** [jannikbuschke/formik-antd#32]
Hello! Do you have any plans to wrap the Antd Table component? I'm looking to build a form with the ability to add/delete identical objects without using arrays of multiple fields (rather using a table instead). Thanks!

**Comment by jannikbuschke** [comment]
Currently planned are only components that directly change some state (shown in the README). Here the api, implementation and usefulness is clear.

Tables or list components _could_ be an interesting addition. But I am not yet sure how these components would work and if its possible to "get them right".

Considering the Antd table I can imaging binding it's `datasource` property to some specific form field. 
Is this already useful?

I would also imagine we want some solutions for adding/removing items (ideally with a declarative syntax) and editing rows/cells.

Im open for ideas.

**Comment by delyanr** [comment]
I would imagine the following capabilities:
- Separate button to ADD new blank rows
- Each row is composed of fields that could be any of the core components (e.g. mix of Input and Rate), but if that's too difficult maybe only selected subset
- Each row will have a separate actions column for EDIT and DELETE
- Ideally also, when in EDIT mode for specific row, fields become visible and can be changed; otherwise they fall back to the default `AntD Table` children

Now this can be linked via `dataSource` and then back to `formik` as an array of objects.

**Comment by jannikbuschke** [comment]
Im currently implementing a table component:

here is some sample code that can be used in v.1.7.0-beta.0

```
import { Table, AddRowButton, RemoveRowButton, Form, Input } from "formik-antd"
import { Formik } from "formik"
import * as React from "react"
import "./table.css"

export function SampleTable() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        flex: 1,
        justifyContent: "center",
      }}
    >
      <Formik
        initialValues={{
          tableData: [
            {
              name: "item 1",
              description: "lorem ipsum",
            },
          ],
        }}
        onSubmit={() => {}}
      >
        <Form>
          <AddRowButton
            name="tableData"
            style={{ marginBottom: 20 }}
            createNewRow={() => ({
              name: "new",
              description: "",
            })}
          >
            Add
          </AddRowButton>
          <Table
            rowKey={(row, index) => "" + index}
            style={{ width: 600 }}
            size="small"
            pagination={false}
            columns={[
              {
                width: 100,
                title: "Name",
                key: "name",
                render: (text, record, i) => (
                  <Input
                    style={{ border: "none" }}
                    name={`tableData.${i}.name`}
                  />
                ),
              },
              {
                title: "Description",
                key: "description",
                render: (text, record, i) => (
                  <Input
                    style={{ border: "none" }}
                    name={`tableData.${i}.description`}
                  />
                ),
              },
              {
                width: 32,
                key: "actions",
                align: "right",
                render: (record, index) => (
                  <RemoveRowButton
                    style={{ border: "none" }}
                    icon="delete"
                    name="tableData"
                    index={index}
                  />
                ),
              },
            ]}
            name="tableData"
          />
        </Form>
      </Formik>
    </div>
  )
}
```

feel free to comment here on the api or here #106

**Comment by jannikbuschke** [comment]
Implemented in v1.7

**Comment by maglini** [comment]
RemoveRowButton doesn't work correctly.  It removes the previous row instead of the current. How to fix it?

**Comment by jannikbuschke** [comment]
in this example it seems to work, can you give me a reproduction?
https://codesandbox.io/s/github/jannikbuschke/formik-antd-example?file=/src/index.tsx
