### ISSUE TITLE
Add source files as part of npm package

### ISSUE THREAD

**Issue by vincaslt** [jannikbuschke/formik-antd#38]
Please add source files to node_modules package, when publishing the package to npm. Because they are not published, I'm unable to inspect the non-compiled source of the package from my editor and my build is throwing warnings because source map files are referring to source files which are not there.

This is the current file stucture:

![image](https://user-images.githubusercontent.com/944727/57585729-b50ed080-74f4-11e9-8e50-4dcd8e16374e.png)

Otherwise, nice lib, I'm having a pleasant time using it so far.

**Comment by jannikbuschke** [comment]
Thank you for reporting the issue and giving feedback!

Is this about including TypeScript or the transpiled js files as sources?

Something like this https://stackoverflow.com/questions/31642477/how-to-publish-a-npm-package-with-distribution-files probably gives the solution I guess.

**Comment by vincaslt** [comment]
The actual typescript files. I think sourcemaps are referring to `../src/<file>.tsx`.

**Comment by jannikbuschke** [comment]
I just published preview 4 which includes the original src folder:
![image](https://user-images.githubusercontent.com/5894881/57970471-d69f0a80-7981-11e9-8058-65a37de01099.png)

Does this removes the warnings/errors?

**Comment by vincaslt** [comment]
Yes it did
