### ISSUE TITLE
Publishing / Testing local formik-antd fork from another Local Project

### ISSUE THREAD

**Issue by jwmann** [jannikbuschke/formik-antd#4]
I was considering adding some PRs but I like to be able to test local changes in my current project prior to submitting the PR.

I know in package.json you can reference another local file / directory as the source of the node module but I tried it and it doesn't seem to build well.
I get errors like 

```
Uncaught TypeError: this.props.formik.registerField is not a function at FieldInner.componentDidMount
```

If I use the normal package installed via npm itself, I don't get these errors.

Maybe I need to publish / build the project first? Not sure.

**Comment by jannikbuschke** [comment]
Just using npm for local package references (via npm install file:... for example) sucks. The setup will most likely end up with two versions of each library you are using (for example two versions of react and two versions of formik) and then above error can occur.

 You can use [lerna](https://github.com/lerna/lerna) for a sophisticated setup. Im actually writing a blog post about it.

The idea is you have one application project and one module project (in this case formik-antd).
inside the formik-antd you can run `tsc --watch` to constantly build and the app project is a normal react application (i.e. create-react-app) that references the module with the help of lerna locally. The app project gets the updates immediatly.

**Comment by jwmann** [comment]
That sounds super useful but I feel like it's a bit overkill just for a quick test.
Unless there's something I'm missing.

**Comment by jannikbuschke** [comment]
It may sound a bit overkill. Especially finding a practical setup is hard and it took me quite some time.

As seen in https://github.com/jannikbuschke/formik-antd this is a powerful setup and it actually is pretty easy to use.

I just published a blogpost about the setup: https://www.jannikbuschke.de/blog/monorepo-with-lerna-react-and-typescript/

You can combine it with git submodules (https://www.jannikbuschke.de/blog/git-submodules/). This would allow you to include formik-antd by its source, so you don't need to wait for new releases.

**Comment by jwmann** [comment]
Thanks for this, I'm definitely going to check out the blog post.
Just a heads up I believe you meant to link https://github.com/jannikbuschke/formik-antd-playground

Your original link was just this repo 😛

**Comment by jannikbuschke** [comment]
correct :)

**Comment by pavanagrawal123** [comment]
@jannikbuschke Trying to test #68 locally, but the changes for modular imports seem to break the lerna playground... Any insight? Thanks :)

**Comment by jannikbuschke** [comment]
Y, something seems to be broken.
However you should be able to test against master (version 1.2 I think) or?

**Comment by jannikbuschke** [comment]
Actually it works for me. I deleted /lib and /es folders,
and run
```
npm run bootstrap
npm run tsc
npm run start
```

**Comment by pavanagrawal123** [comment]
@jannikbuschke are you using the modular imports + the babel plugin?

**Comment by jannikbuschke** [comment]
I would recommend to test against master without modular imports + babel plugin.

**Comment by pavanagrawal123** [comment]
@jannikbuschke would you happen to know what is causing the error below?
![image](https://user-images.githubusercontent.com/17802917/61254041-cd83ad00-a728-11e9-9d8a-171cfa4d253c.png)
I'm on master for formik-antd and my react app is a pretty basic normal react app. This error does not occur when I use the package from npm, it only occurs when i try to install from source with lerna.

**Comment by jannikbuschke** [comment]
@pavanagrawal123 this happens if some library (either react or formik in this case I think) is brought in twice by the packages.
The playground has `/app/` and `/formik-antd/` as a package. Both have dependencies on react and formik. If when running the whole thing `app` uses a different copy of `react` (or `formik`) than `formik-antd`, then above error occurs.

This is why we need to run `lerna bootstrap --hoist` in the root. `lerna` will look at all dependencies and will pick one that will be used by all packages.
Running `npm run bootstrap` in root should solve your problem (npm script that runs `lerna bootstrap --hoist`)
