### ISSUE TITLE
DatePicker not formatting correctly

### ISSUE THREAD

**Issue by mfasanya** [jannikbuschke/formik-antd#48]
When using the DatePicker through formik it isn't formatted correctly and also when clicked the datepicker doesn't appear. 

With formik-antd
<img width="561" alt="Screenshot 2019-05-18 at 18 50 49" src="https://user-images.githubusercontent.com/6720841/57973242-e75d7980-799d-11e9-9c4d-a6c2ffd1aaed.png">

Standard antd
<img width="525" alt="Screenshot 2019-05-18 at 18 51 03" src="https://user-images.githubusercontent.com/6720841/57973245-f3e1d200-799d-11e9-872c-c6ff8943d3e5.png">

<img width="568" alt="Screenshot 2019-05-18 at 18 51 05" src="https://user-images.githubusercontent.com/6720841/57973248-f6dcc280-799d-11e9-8b81-de17edaec598.png">

**Comment by mfasanya** [comment]
I tried taking the formik-antd DatePicker code and pasting it locally. That seems to work fine, perhaps the npm module isn't up to date?

**Comment by jannikbuschke** [comment]
I cant reproduce the issue you are seeing (using v1.0.0-preview.4).

Can you give some sample code or try to reproduce it in codesandbox: https://codesandbox.io/s/x2941k7vpz

**Comment by mfasanya** [comment]
I'm not able to recreate. But I have isolated the issue, using create-react-app with babel-plugin-import. Whilst if I just import the css then this issue doesn't occur

**Comment by jannikbuschke** [comment]
I think then this is a duplicate of #24

**Comment by mfasanya** [comment]
Yep it's a duplicate, for now I've just stopped using babel-plugin-import
