### ISSUE TITLE
<Select.Option/> support?

### ISSUE THREAD

**Issue by jeessy2** [jannikbuschke/formik-antd#51]
Select don't support Select.Option!  
I find "Select.renderOptions" in Select.tsx, 
But not everybody know this.  Because in ant design, we use <Select.Option>

My code:

```
import {Select} from "@jbuschke/formik-antd";
```
```
<Select name='sex'>
 {
  Select.renderOptions([{label:'male', value:'M'}])
 }
</Select>
```

**Comment by jannikbuschke** [comment]
Currently its possible to just use Ant Designs Select.Option in this case.
It can also combined with renderOptions:

```jsx
import {  Select } from "@jbuschke/formik-antd";
import {  Select as $Select } from "antd";

// ....
<Select name="select" style={{ width: 200 }} placeholder="Select">
  <$Select.Option value={"asd"}>asd</$Select.Option>
    {Select.renderOptions([
      { label: "foo" },
      { label: <h3>bar</h3>, value: 2 },
      { disabled: true, label: "baz" }
    ])}
</Select>
```

https://codesandbox.io/s/formikantd-uuv9m

**Comment by jannikbuschke** [comment]
I will most likely also statically set Ant Designs Select.Option on the formik-antds one, so that you can just use `Select.Option` without imporing Select from ant design. See #37

**Comment by jeessy2** [comment]
Okay, when is it released

**Comment by jannikbuschke** [comment]
Now

**Comment by RomaSto** [comment]
My code:           
                          <Select
                            defaultValue="Sunday"
                          >
                            <Select.Option value="Sunday">Sunday</Select.Option>
                            <Select.Option value="Monday">Monday</Select.Option>
                            <Select.Option value="Tuesday" >Tuesday</Select.Option>
                            <Select.Option value="Wednesday">Wednesday</Select.Option>
                          </Select>
Error:
Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)
