### ISSUE TITLE
DatePicker mode="year" doesnt work

### ISSUE THREAD

**Issue by RomaSto** [jannikbuschke/formik-antd#53]
MY code: `<DatePicker mode="year" name="eventYear" placeholder="Event year" />`

Year can`t be selected

**Comment by jannikbuschke** [comment]
This seems to be an ant design issue.
There are several issues; its a little scattered:
https://github.com/ant-design/ant-design/issues/11735#issuecomment-412543655
https://github.com/ant-design/ant-design/issues/4524
https://github.com/ant-design/ant-design/issues/15572
https://github.com/ant-design/ant-design-pro/issues/4268
https://github.com/ant-design/ant-design/issues/11053
https://github.com/ant-design/ant-design/pull/16984

In the last one some context is given. A proper YearPicker seems to only come in ant design 4. The DatePicker mode prop seem to only have a visual effect but doesn't really work

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16984
