### ISSUE TITLE
Error using Select component

### ISSUE THREAD

**Issue by RomaSto** [jannikbuschke/formik-antd#54]
My code:           
                          <Select
                            defaultValue="Sunday"
                          >
                            <Select.Option value="Sunday">Sunday</Select.Option>
                            <Select.Option value="Monday">Monday</Select.Option>
                            <Select.Option value="Tuesday" >Tuesday</Select.Option>
                            <Select.Option value="Wednesday">Wednesday</Select.Option>
                          </Select>
Error:
Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)

**Comment by jannikbuschke** [comment]
Your code should work. The "simple select" example looks pretty much the same here https://codesandbox.io/s/x2941k7vpz

Setting the defaultValue should be done on the Formik initialValues props imho. We might need to improve the Select prop api here (i.e. by removing defaultValue)

Your code however looks correct. So pls provide more context or a failing example on codesandbox.

**Comment by jannikbuschke** [comment]
Not reproducable. Feel free to open again if the issue persists (pls provide a repro then)

**Comment by dbousamra** [comment]
I also have this issue.

**Comment by jordn** [comment]
also have this issue. haven't investigated

**Comment by paulonteri** [comment]
I managed to solve this problem by adding the name prop to the `Form.Item` & `Select`

```
  <Form.Item name="xyz">
      <Select name="xyz">
          <Select.Option value={1}>1</Select.Option>
          <Select.Option value={2}>2</Select.Option>
      </Select>
  </Form.Item>
```
