### ISSUE TITLE
Error when using Select component

### ISSUE THREAD

**Issue by RomaSto** [jannikbuschke/formik-antd#55]
My code:           
                          <Select
                            defaultValue="Sunday"
                          >
                            <Select.Option value="Sunday">Sunday</Select.Option>
                            <Select.Option value="Monday">Monday</Select.Option>
                            <Select.Option value="Tuesday" >Tuesday</Select.Option>
                            <Select.Option value="Wednesday">Wednesday</Select.Option>
                          </Select>
Error:
Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)

**Comment by dbousamra** [comment]
I have this issue too.

**Comment by jannikbuschke** [comment]
duplicat: https://github.com/jannikbuschke/formik-antd/issues/54
