### ISSUE TITLE
Using react-input-mask for Input

### ISSUE THREAD

**Issue by iloveip** [jannikbuschke/formik-antd#69]
Hi there,

Is it possible to use `formik-antd` with [react-input-mask](https://github.com/sanniassin/react-input-mask)?

Here is an [example](https://codesandbox.io/s/react-input-mask-wantd-final2-8ihln?fontsize=14) of `react-input-mask` with `antd`.

When I try to add it to `formik-antd`, I can see the mask onFocus, but it doesn't work onChange. Here is the [demo](https://codesandbox.io/s/add-formik-antd-ces36?fontsize=14).

**Comment by jannikbuschke** [comment]
mh not sure about this one.
Currently the onChange handlers are not yet properly exposed (its in progress, I can release a new version for the Input component soon).

also it seems that react-input-mask would need to set the value of the component correct?
So basically react-inpu-mask becomes the controlling instance of the Input. Not sure about the consequences.

**Comment by iloveip** [comment]
Thank you very much for your reply. Are there any other libraries for masking inputs, compatible with `formik-antd`?

**Comment by jannikbuschke** [comment]
Not that I am aware of.

Is react-input-mask compatible with ant design? If so I would recommend to create a custom component for your specific use case and not use formik-antd in this specific case. Or wait until the onChange functionality is released and try agaiin.

Also an alternative could be to use the InputNumber component which has a format property to allow customizing what is being rendered. With this I can imagine applying some mask to the final output.

**Comment by iloveip** [comment]
Ok, thank you very much!

**Comment by iloveip** [comment]
Actually, I was able to get it work with `onChange={handleChange}`, here is the [demo](https://codesandbox.io/s/formik-antd-wreact-input-mask-mlloq?fontsize=14).

I have one more question, is it possible to parse the value, submitted through `formik-antd` Input? Something like this:

```
parse={value =>
  value
    .replace(/\)/g, "")
    .replace(/\(/g, "")
    .replace(/-/g, "")
    .replace(/ /g, "")
}
```

**Comment by jannikbuschke** [comment]
theoretically you can change the input:

https://codesandbox.io/s/formik-antd-wreact-input-mask-in0rv

With your above code setting the `changedValue` creates an error (probably due to input-mask). 

Just as a side-node: overriding onChange here and setting formik values directly (via onChange or setField) is exactly what `formik-antd` is designed for.
So basically you dont really need `formik-antd`. You are basically creating a custom integration between antd and formik. Im not sure if you actually need `formik-antd`

**Comment by iloveip** [comment]
Ok, I see, thank you very much.
