### ISSUE TITLE
Radio component as Radio.Button produces "undefined" form items

### ISSUE THREAD

**Issue by victorferreira** [jannikbuschke/formik-antd#70]
If I have a Radio.Group on my form, whenever I change the value of the radio it creates a "undefined" attribute in the values object. Part of the behaviour is correct, it changes the value of the category to whichever value I have selected at the time, but also creates a new attribute called "undefined".  I have to manually remove to the key from the object to correctly submit the form.

I even created a sandbox to demonstrate the issue: https://codesandbox.io/s/angry-shockley-f513c

**Comment by jannikbuschke** [comment]
I never checked the Radio item itself.
I would recommend to use the Radio.Button component like so
```
      <Form {...formItemLayout}>
          <Radio.Group name="category">
            <Radio.Button value={"A"}>A</Radio.Button>
            <Radio.Button value={"B"}>B</Radio.Button>
```

Usage of Radio is something I would need to look at.

**Comment by victorferreira** [comment]
Thank you!

The workaround a used to fix it was to add a name prop in every Radio item, but it seemed very redundant to me.

```
<Form {...formItemLayout}>
          <Radio.Group name="category">
            <Radio name="category" value={"A"}>A</Radio>
            <Radio name="category" value={"B"}>B</Radio>
```

Using Radio.Button seems to be a better solution.

**Comment by jannikbuschke** [comment]
Actually the `name` prop for the `Radio` component is always required and by design.
Using `Radio.Button` seems to be the preferred way on how to use a RadioButton Group.
