### ISSUE TITLE
Problem validating an Input wrapped by Form.Item

### ISSUE THREAD

**Issue by tsaiDavid** [jannikbuschke/formik-antd#71]
Hi there - thanks for the work on `formik-antd`!

I'm running into a slight snag - how might I utilize the `validate` prop on an `<Input />` component - all while utilizing a `<Form.Item>` to wrap it?

I would like to provide a label for a field and perform field-level validation on it, but it looks like if the name property on `Form.Item` and `Input` are identical, any errors do not make it up into the Formik state (as shown by the debugger component).

I've provided an example here:
https://codesandbox.io/s/formikantd-j4b4m?fontsize=14

**Comment by jannikbuschke** [comment]
Thanks for the repro, this seems to be a bug.

**Comment by jannikbuschke** [comment]
Its a bit weird, but inlining the validation callback solves the issue:
https://codesandbox.io/s/formikantd-oz3yq

Not sure why
