### ISSUE TITLE
Submit Button default disabled behavior

### ISSUE THREAD

**Issue by voxtex** [jannikbuschke/formik-antd#73]
It doesn't seem to make sense to disable SubmitButton by default when the form is invalid. What ends up happening is that the form is immediately invalid, and since errors don't show up on fields unless they have been touched (focused or submit button pressed), it is impossible to tell which form fields need to be fixed and you can't click submit to check.

I propose remove isValid check or changing it to (!isValid && submitCount > 0) or something similar.

**Comment by jannikbuschke** [comment]
I also regularly overwrite the default behavior (i.e. by using disable={true})

(!isValid && submitCount > 0) seems to be an improvement. Maybe there are also better implementations. Feel free to open a pull request.

It would also be good to here from others what I good default behavior would be.
