### ISSUE TITLE
any breaking changes in 1.3?

### ISSUE THREAD

**Issue by jannikbuschke** [jannikbuschke/formik-antd#75]
If anyone by change reads this, can you report if version 1.3 works or has any problems that have not been present in 1.2?

The underlying way of exporting components changed, but there shouldnt be any breaking changes.

Any feedback is appreciated (also just "works")

**Comment by claneo** [comment]
While I'm using `babel-plugin-import` (as mentioned in [#63](https://github.com/jannikbuschke/formik-antd/issues/63#issuecomment-506563291)), it breaks in 1.3. I'm not sure if someone copied this config.

Another situation is someone may use the import style like `import { Input } from '@jbuschke/formik-antd/es/Input'` to reduce bundle size. It won't work too.

**Comment by jannikbuschke** [comment]
Can you try following `.babelrc`
```
{
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": true
      }
    ] // `style: true` for less
  ]
}
```

`config-overrides.js`:

```js
const { override, fixBabelImports } = require('customize-cra');

module.exports = override(
    // add webpack-ant-icon-loader
    (config) => {
        config.module.rules.push({
            loader: 'webpack-ant-icon-loader',
            enforce: 'pre',
            include: [
                require.resolve('@ant-design/icons/lib/dist')
            ]
        });
        return config;
    },
    fixBabelImports('antd', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: 'css',
    }),
    fixBabelImports('formik-antd',
        {
            libraryName: '@jbuschke/formik-antd',
            style: "css",
            // style: true
            // style: 'css',
            libraryDirectory: 'es'
        },
    ),
);
```

```json
  "devDependencies": {
    "babel-plugin-import": "1.12.0",
    "customize-cra": "0.2.14",
    "react-app-rewired": "2.1.3",
    "source-map-explorer": "2.0.1",
    "webpack-ant-icon-loader": "1.0.8"
  }
```

The icon loading doesnt really work though

**Comment by claneo** [comment]
It works for me. In fact, I have already changed my babel config after 1.3.0 released.

`.babelrc` won't work if you are using `create-react-app`, just use `config-overrides.js`.

As for `webpack-ant-icon-loader`, what it do is just split icon to another chunk, not removing unused icons, so total bundle size won't reduce. Only [this method](https://github.com/jannikbuschke/formik-antd/issues/63#issuecomment-515123092) works.
