### ISSUE TITLE
Using antd style customization

### ISSUE THREAD

**Issue by Mikecoon** [jannikbuschke/formik-antd#76]
Getting started documentation says:

> Add import "antd/dist/antd.css to your index.js file (or look at https://ant.design/docs/react/getting-started for other options).

And Antd's documentation has:
https://ant.design/docs/react/use-with-create-react-app#Customize-Theme

It also gives the ability to reduce the amount of css code which should be included by adding only used components.
https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides

But when I use formik-antd I lose this and can't customize theme anymore :(

Any solution for that?

**Comment by jannikbuschke** [comment]
Modular imports are now possible. This maybe also helps with custom themes.
Can you have a look at #75 and see if you can find a configuration that allows custom theming?

**Comment by Mikecoon** [comment]
Oh thanks! Works :)
