### ISSUE TITLE
Lack of animations of datepicker

### ISSUE THREAD

**Issue by Mikecoon** [jannikbuschke/formik-antd#77]
Original datepicker has tidy animation when it opens and closes up.
This datepicker appears immediately, why?

**Comment by jannikbuschke** [comment]
Can you repro here: https://codesandbox.io/s/x2941k7vpz?
for me it shows animations

**Comment by Mikecoon** [comment]
Yes, if you remove ` showTime={true} ` prop closing animation disappears for the first time, then it's okay.
I guess my issue related to overrided `onBlur` and `onFocus`  props. 
Is there any note, how to handle them properly?

**Comment by jannikbuschke** [comment]
Do you still face this issue?
If so can you reproduce here https://codesandbox.io/s/formikantd-v8tpq ?

**Comment by Mikecoon** [comment]
Yes, I guess because it spends time to drop an error to console, I'm not sure but probably it does it in the UI thread or something.

So yes, the most first open performs with cut animation.

**Comment by jannikbuschke** [comment]
I don't really recognize performance issues with the animations. I also do not see any error on the console. Maybe its browser related?

**Comment by Mikecoon** [comment]
Sorry, I meant warning.
It says:

```
index.js:27 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Animate
```

**Comment by jannikbuschke** [comment]
Does this also happen with the plain ant design component?
https://codesandbox.io/s/formikantd-v8tpq
For me it also prints a warning (but I dont really see any performance issue)

**Comment by jannikbuschke** [comment]
This seems to not be a problem with `formik-antd`.
