### ISSUE TITLE
Checkbox.Group errors

### ISSUE THREAD

**Issue by RomaSto** [jannikbuschke/formik-antd#80]
Checkbox.Group with options as array of objects throws
TypeError
state.value.indexOf is not a function

https://codesandbox.io/s/inspiring-herschel-0s72m

Checkboxes nested into a group throw
TypeError
checkboxGroup.value.indexOf is not a function

https://codesandbox.io/s/naughty-proskuriakova-pu22z

**Comment by jannikbuschke** [comment]
@RomaSto sorry for the late response.
All `formik-antd` components need a `name: string` property that syncs the state to formik.
This solves both your codesandboxes.

i.e. this works:
```
import React from "react";
import ReactDOM from "react-dom";
import { Formik } from "formik";
import { Checkbox } from "formik-antd";
const Form = () => (
  <div>
    <Formik
      render={() => (
        <Checkbox.Group
          name="myfieldname"
          options={[{ label: "Analyst", value: "Analyst" }]}
        />
      )}
    />
  </div>
);

const rootElement = document.getElementById("root");
ReactDOM.render(<Form />, rootElement);

```

**Comment by jannikbuschke** [comment]
Feel free to reopen if there still is an issue
