### ISSUE TITLE
Babel import styles not working in production build

### ISSUE THREAD

**Issue by JeffJankowski** [jannikbuschke/formik-antd#92]
Here is my `config-overrides.js`:

```
module.exports = override(
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: {
      hack: `true; @import "${path.resolve(__dirname, './src/theme.less')}";` // Override with less file
    }
  }),
  fixBabelImports('antd', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true
  }),
  fixBabelImports('formik-antd', {
    libraryName: '@jbuschke/formik-antd',
    style: true,
    libraryDirectory: 'es'
  })
);
```

Everything is working great with `yarn start`, but I'm missing styles for `formik-antd` components when creating a production build (`yarn build`).

Just saw this comment, which looks like they're having the same issue: https://github.com/jannikbuschke/formik-antd/issues/63#issuecomment-543891530

The next comment in that thread (@edongashi) has suggestions which did not fix the problem.

> @thj-dk is your build script in `package.json` set to `"build": "react-app-rewired build"`?
> 
> Also try setting `style: 'css'` in `fixBabelImports` to see if it makes any difference.

**Comment by JeffJankowski** [comment]
Visual results on production build are identical to if I excluded the babel imports block altogether:
```
fixBabelImports('formik-antd', {
    libraryName: '@jbuschke/formik-antd',
    style: true,
    libraryDirectory: 'es'
  })
```

**Comment by jannikbuschke** [comment]
thanx to @edongashi this is working now (v.1.5.4).
