### ISSUE TITLE
Why do we need fix babel imports for formilk-antd?

### ISSUE THREAD

**Issue by rszemplinski** [jannikbuschke/formik-antd#96]
Just curious why we need to do this to use your package?

```js
fixBabelImports('formik-antd',
        {
            libraryName: '@jbuschke/formik-antd',
            libraryDirectory: 'es'
            style: "css",
        },
    )
);
```

I couldn't find anything in the docs that explain the reasoning behind this.

**Comment by jannikbuschke** [comment]
This step is optional. If you do not want to include the full antd.css stylesheets (or the specific component stylesheets) you can let babel do the imports for you.

**Comment by rszemplinski** [comment]
But doesn't this

```js
 fixBabelImports('antd', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: 'css',
    }),
```

Do exactly that?

**Comment by jannikbuschke** [comment]
Did you test this?

I think (I am not an expert on this topic), in this case only original antd imports would properly work. But this library re-exports antd components, so a `import {Input} from "@jbuschke/formik-antd` would be undetected by babel and the styles could be missing.

**Comment by rszemplinski** [comment]
I have not tested this yet. I will get back to you tonight with the results. Thanks for working with me. This is more for my curiosity and not questioning your work. 😅

**Comment by jannikbuschke** [comment]
closing for housekeeping. Feel free to reopen if there is something unclear.
